function fnIdiomaIngles(){
    document.getElementById("menu1").innerText = "Home"
    document.getElementById("menu2").innerText = "Properties"
    document.getElementById("menu3").innerText = "About Us"
    document.getElementById("menu4").innerText = "Contact"
    document.getElementById("menu5").innerText = "Find Your Dream Home"
    document.getElementById("menu6").innerText = "Explore our wide range of properties and find the perfect home for you."
    document.getElementById("menu7").innerText = "Search Properties"
    document.getElementById("menu8").innerText = "Learn More"
    document.getElementById("menu9").innerText = "Get in touch with us today!"
    document.getElementById("menu10").innerText = "Contact Us"
    document.getElementById("menu11").innerText = "Phone"
    document.getElementById("menu12").innerText = "Office"
    document.getElementById("menu13").innerText = "Subscribe to our newsletter for the latest updates on new features and product releases."
    document.getElementById("menu14").innerText = "Subscribe"
    document.getElementById("menu15").innerText = "All rights reserved."
}

function fnIdiomaPortugues(){
    document.getElementById("menu1").innerText = "Inicial"
    document.getElementById("menu2").innerText = "Imóveis"
    document.getElementById("menu3").innerText = "Sobre nós"
    document.getElementById("menu4").innerText = "Contato"
    document.getElementById("menu5").innerText = "Encontre a casa dos seus sonhos"
    document.getElementById("menu6").innerText = "Explore nossa ampla variedade de imóveis e encontre a casa perfeita para você."
    document.getElementById("menu7").innerText = "Pesquise Imóveis"
    document.getElementById("menu8").innerText = "Saiba Mais"
    document.getElementById("menu9").innerText = "Entre em contato conosco hoje mesmo!"
    document.getElementById("menu10").innerText = "Entre em contato"
    document.getElementById("menu11").innerText = "Telefone"
    document.getElementById("menu12").innerText = "Escritório"
    document.getElementById("menu13").innerText = "Assine nossa newsletter para receber as últimas atualizações sobre novos recursos e lançamentos de produtos."
    document.getElementById("menu14").innerText = "Cadastrar"
    document.getElementById("menu15").innerText = "Todos os direitos reservados"
}